✨ USD0++ Cauldron
Abracadabra-money/abracadabra-money-contracts pull request #222
Opened 2024-10-02 13:13 UTC by 0xCalibur

2024-10-02 17:59 UTC, 0xmDreamy approved these changes

2024-10-03 13:12 UTC, 0xm3rlin requested changes

2024-10-03 13:12 UTC, 0xm3rlin commented on script/MagicUSD0ppCauldron.s.sol
> +        collateral = 0xdB36f69B88Ec1388dBFAc90132CD396FD4749963; // MagicUSD0++
Incorrect -> implementation not proxy address of UUPS proxy requires changes of all swappers as well

2024-10-03 13:12 UTC, 0xm3rlin commented on script/MagicUSD0ppCauldron.s.sol
> +                abi.encode(string.concat(name, "/USD"), collateral, chainlinkAggregator)
redeploy necessary

2024-10-03 13:12 UTC, 0xm3rlin commented on script/MagicUSD0ppCauldron.s.sol
> +            IERC20(collateral),
redeploy necessary

2024-10-03 13:12 UTC, 0xm3rlin commented on script/MagicUSD0ppCauldron.s.sol
> +            abi.encode(box, collateral, mim)
redeploy necessary

2024-10-03 13:12 UTC, 0xm3rlin commented on script/MagicUSD0ppCauldron.s.sol
> +            abi.encode(box, collateral)
redeploy necessary

2024-10-03 14:58 UTC, 0xm3rlin approved these changes

2024-10-07 12:22 UTC, merged